title: Leask
short_name: Leask
description: break the wall or bring the war
display_name: 'Sixia "Leask" Huang'
bio: break the wall or bring the war
lang: zh-CN
url: 'https://leask.github.io'
baseurl: ''
avatar: '/assets/avatar/profile.png'
social_links:
  - label: X
    kind: x
    url: 'https://x.com/LeaskH/'
  - label: GitHub
    kind: github
    url: 'https://github.com/leask/'
  - label: Telegram
    kind: telegram
    url: 'https://t.me/Leask'
  - label: Email
    kind: email
    url: 'mailto:i@leaskh.com'
  - label: Phone
    kind: phone
    url: 'tel:+19715177039'
copyright: '© 2005-2026 Sixia "Leask" Huang'
permalink: /:year/:month/:day/:title/
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
paginate: 10
paginate_path: '/page/:num/'
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
exclude:
  - .history
  - reports
  - tools
  - vendor
  - node_modules
  - README.md
  - LICENSE
