#!/bin/sh
# Flora database backup by LeaskH.com

echo 'Backup session started.'

echo 'Backing up www.leaskh.com database...';
mysqldump -h localhost -uleask -p******************************* --database leaskhco_wp   > /leaskh.com/dbackup_archive/leaskh_com_wp.sql;
sed -i 's/^-- Dump completed on .*//' /leaskh.com/dbackup_archive/leaskh_com_wp.sql;

echo 'Adding backup to git repository...';
git commit -a -m "Database backup: `date`" 1> /dev/null

echo 'All backup have been finished.';

